"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RedisChannels = exports.SocketEvents = void 0;
var SocketEvents;
(function (SocketEvents) {
    SocketEvents["CONNECTION"] = "connection";
    SocketEvents["DISCONNECT"] = "disconnect";
    SocketEvents["ERROR"] = "error";
    SocketEvents["AUTH_SUCCESS"] = "auth:success";
    SocketEvents["AUTH_ERROR"] = "auth:error";
    SocketEvents["ORDER_CREATED"] = "order:created";
    SocketEvents["ORDER_UPDATED"] = "order:updated";
    SocketEvents["ORDER_STATUS_CHANGED"] = "order:status_changed";
    SocketEvents["ORDER_PAID"] = "order:paid";
    SocketEvents["ORDER_CANCELLED"] = "order:cancelled";
    SocketEvents["SCANNER_SESSION_START"] = "scanner:session_start";
    SocketEvents["SCANNER_SESSION_STARTED"] = "scanner:session_started";
    SocketEvents["SCANNER_SESSION_END"] = "scanner:session_end";
    SocketEvents["SCANNER_SESSION_ENDED"] = "scanner:session_ended";
    SocketEvents["SCANNER_SCAN"] = "scanner:scan";
    SocketEvents["SCANNER_SCAN_RESULT"] = "scanner:scan_result";
    SocketEvents["SCANNER_CONFIRM_REQUIRED"] = "scanner:confirm_required";
    SocketEvents["SCANNER_CONFIRM"] = "scanner:confirm";
    SocketEvents["SCANNER_PLAY_SOUND"] = "scanner:play_sound";
    SocketEvents["SCANNER_ERROR"] = "scanner:error";
    SocketEvents["SUPPORT_NEW_MESSAGE"] = "support:new_message";
    SocketEvents["SUPPORT_MESSAGE_READ"] = "support:message_read";
    SocketEvents["SUPPORT_CHAT_ASSIGNED"] = "support:chat_assigned";
    SocketEvents["SUPPORT_CHAT_CLOSED"] = "support:chat_closed";
    SocketEvents["SUPPORT_TYPING"] = "support:typing";
    SocketEvents["ADMIN_CONNECTED"] = "admin:connected";
    SocketEvents["ADMIN_ACTION"] = "admin:action";
    SocketEvents["BOT_STATUS_UPDATE"] = "bot:status_update";
    SocketEvents["BOT_USER_ACTION"] = "bot:user_action";
    SocketEvents["NOTIFICATION_SENT"] = "notification:sent";
    SocketEvents["NOTIFICATION_READ"] = "notification:read";
    SocketEvents["DATA_UPDATE"] = "data:update";
    SocketEvents["STATS_UPDATE"] = "stats:update";
    SocketEvents["BROADCAST_MESSAGE"] = "broadcast:message";
    SocketEvents["BROADCAST_NOTIFICATION"] = "broadcast:notification";
})(SocketEvents || (exports.SocketEvents = SocketEvents = {}));
var RedisChannels;
(function (RedisChannels) {
    RedisChannels["BOT_UPDATES"] = "bot:updates";
    RedisChannels["ORDER_UPDATES"] = "order:updates";
    RedisChannels["SCANNER_UPDATES"] = "scanner:updates";
    RedisChannels["SUPPORT_UPDATES"] = "support:updates";
    RedisChannels["NOTIFICATION_QUEUE"] = "notification:queue";
    RedisChannels["CACHE_INVALIDATION"] = "cache:invalidation";
})(RedisChannels || (exports.RedisChannels = RedisChannels = {}));
//# sourceMappingURL=events.js.map